# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.7
  - nightly

notifications:
  email: false
matrix:
  allow_failures:
    - julia: nightly
branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags
after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("EnhancedGJK")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
